### ISSUE TITLE
Дз юнити 1

### ISSUE THREAD

**Issue by Tizz1e** [Tizz1e/Kalugin-Alexey-homework#9]
@shadowAnonim

**Comment by shadowAnonim** [comment]
У тебя не выгрузились некоторые папки, проект открыть невозможно.
Вероятно это из-за плохого gitignore, перезагрузи проект. пожалуйста.

**Comment by Tizz1e** [comment]
я попросил друга выгрузить проект, т.к. даже с гитигнором под юнити гитхаб продолжал жаловаться на количество файлов(я сдаю через веб). может подскажешь, что можно сделать?
